import org.apache.hadoop.fs.PathIOException;
public class FunctionUse1742 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getMessage();
}
}